---
# tasks file for docker-conf
#- name: add docker repository
#  yum_repository:
#          name: docker_repo
#          description: Docker YUM Repo
#          file: ansible_repos
#          baseurl: "{{ base_url }}"
#          gpgcheck: yes
#          gpgkey: "{{ gpg_key }}"
#          enabled: yes
- name: install python and docker
  package:
          name:
                  - python3.7
                  - python-devel
                  - python-pip
                  - docker
          state: present
  notify: Start Docker
- name: Upgrade pip
  command: pip install --upgrade pip
  changed_when: false
- name: install docker sdk
  become: no
  pip:
          name: docker-py
          state: present
  notify: Start Docker
