---
# tasks file for ec2-provision
- name: aws sdk for python
  pip:
                    name: boto3
                    state: present

- name: Provisioning instances over cloud
  ec2:
                    key_name: "{{ key_name }}"
                    instance_type: "{{ instance_type }}"
                    wait: yes
                    group: "{{ sec_group }}"
                    instance_tags:
                            Name: "{{ item.name }}"
                            Cluster: Kubernetes
                            Node: "{{ item.node }}"
                    assign_public_ip: yes
                    image: "{{ image }}"
                    exact_count: 1
                    count_tag:
                            Name: "{{ item.name }}"
                    region: "{{ region }}"
                    vpc_subnet_id: subnet-50a4ad38
                    aws_access_key: "{{ access_key }}"
                    aws_secret_key: "{{ secret_key }}"
  loop: "{{ x }}"
